export const PROFILE = {
  name: "Bappaditya Maity",
  email: "bappaditya00001@gmail.com",
  phone: "+91 7797707550",
  github: "https://github.com/Mr-Bappa",
  linkedin: "https://www.linkedin.com/in/bappaditya-analytics/",
  tagline: "Analytics Engineer · AI Builder · Data Architect",
  summary:
    "Analytics Engineer with 2+ years designing production-grade ELT/ETL pipelines, dimensional data models, and LLM-assisted analytics systems.",
  stats: {
    experience: "2+",
    savings: "$33M",
    records: "10M+",
    gpa: "8.8",
  },
};

export const JOURNEY = [
  {
    id: 1,
    stop: "01",
    period: "2019 – 2022",
    institution: "Midnapore College",
    degree: "B.Sc in Mathematics",
    gpa: "8.4 / 10",
    color: "violet" as const,
    coursework: ["Calculus", "Linear Algebra", "Statistics", "Real Analysis"],
    highlight: "Foundation in pure mathematics",
  },
  {
    id: 2,
    stop: "02",
    period: "2022 – 2024",
    institution: "NIT Agartala",
    degree: "M.Sc Math & Computing",
    gpa: "8.8 / 10",
    color: "teal" as const,
    coursework: ["Machine Learning", "Optimization", "Algorithms", "Prob. Theory", "Statistical Inference"],
    highlight: "Gold standard — top performance",
  },
  {
    id: 3,
    stop: "03",
    period: "Aug 2024 – Aug 2025",
    institution: "Mu Sigma",
    degree: "Decision Scientist",
    gpa: "Analytics Consulting",
    color: "amber" as const,
    coursework: ["BigQuery", "Apache Airflow", "Power BI", "A/B Testing", "Chi-Square Tests"],
    highlight: "Fortune 500 clients · –70% manual effort",
  },
  {
    id: 4,
    stop: "04",
    period: "Sep 2025 – Present",
    institution: "Axion Ray",
    degree: "Analytics Engineer",
    gpa: "$33M client savings",
    color: "teal" as const,
    coursework: ["dbt", "DuckDB", "LLM Pipelines", "GCP", "OpenAI API", "Data Contracts"],
    highlight: "B2B SaaS · Automotive Analytics",
  },
];

export const DOMAINS = [
  {
    id: "etl",
    icon: "git-branch",
    title: "ETL / ELT Pipelines",
    desc: "Python · Airflow · dbt · GCP · DuckDB",
    detail: "Production-grade pipelines with sub-hour SLAs, schema validation, and full lineage.",
  },
  {
    id: "agents",
    icon: "brain",
    title: "AI Agent Creation",
    desc: "LangChain · RAG · OpenAI · Groq",
    detail: "Agentic systems with tool use, memory, and RAG over structured + unstructured data.",
  },
  {
    id: "finetune",
    icon: "adjustments",
    title: "LLM Fine-tuning",
    desc: "Custom datasets · eval · deploy",
    detail: "Domain-specific fine-tuning with evaluation frameworks and production deployment.",
  },
  {
    id: "modeling",
    icon: "table",
    title: "Dimensional Modeling",
    desc: "Star schema · dbt marts · contracts",
    detail: "Staging → marts architecture with data contracts and governed business logic.",
  },
  {
    id: "bi",
    icon: "chart-bar",
    title: "BI Dashboards",
    desc: "Power BI · KPI modeling · self-serve",
    detail: "Executive dashboards with 20+ KPIs, role-based access, and scheduled refresh.",
  },
  {
    id: "cloud",
    icon: "cloud",
    title: "Cloud Data Platforms",
    desc: "BigQuery · GCS · Parquet · PostgreSQL",
    detail: "Cloud-native data platforms with Parquet optimization and audit layers.",
  },
];

export const SERVICES = [
  {
    id: "etl-pipeline",
    badge: "Open for work",
    badgeType: "open" as const,
    title: "ETL Pipeline Design",
    desc: "End-to-end · production-grade",
    priceINR: 15000,
    priceUSD: 180,
    deliveryDays: 7,
  },
  {
    id: "rag-agent",
    badge: "Fast delivery",
    badgeType: "fast" as const,
    title: "RAG / AI Agent Build",
    desc: "Custom LLM · deployed · tested",
    priceINR: 20000,
    priceUSD: 240,
    deliveryDays: 5,
  },
  {
    id: "dbt-modeling",
    badge: "Open for work",
    badgeType: "open" as const,
    title: "dbt + Data Modeling",
    desc: "Staging → marts · data contracts",
    priceINR: 12000,
    priceUSD: 145,
    deliveryDays: 5,
  },
  {
    id: "dashboard",
    badge: "Popular",
    badgeType: "fast" as const,
    title: "Analytics Dashboard",
    desc: "Power BI · KPI modeling · self-serve",
    priceINR: 10000,
    priceUSD: 120,
    deliveryDays: 4,
  },
];
